Repository AY2021S2-CS2103-T16-1/tp, pull requests merged in 2021-04, with the labels that each got.

#80 Update guide for light and dark mode
  docs/UserGuide.md
Labels: documentation, priority.medium

#79 Remove black bar due to list updating
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: bug, priority.medium

#140 Fix error in mass blacklist in user guide
  docs/UserGuide.md
Labels: priority.medium, type.bug

#138 Add test cases for find
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/ModeOfContactPredicate.java
  src/main/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonBlacklistedPredicate.java
  src/main/java/seedu/address/model/person/predicates/PersonTagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/predicates/PhoneContainsNumbersPredicate.java
  src/main/java/seedu/address/model/person/predicates/ReturnTruePredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/predicates/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/ModeOfContactPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PersonBlacklistedPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PersonTagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/predicates/PhoneContainsNumbersPredicateTest.java
Labels: priority.medium, type.codestyle

#145 Add test cases for sort
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, type.accepted, type.bug, type.codestyle

#141 Fix ambiguities in system messages and user guide for undo
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: priority.low, type.accepted, type.bug

#139 Fix javafx incompatibility
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: priority.high, type.bug

#142 Remove unused commands from user guide
  docs/UserGuide.md
Labels: priority.medium, type.accepted, type.bug

#144 Update find documentation
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  docs/images/findBerniceBlistResult.png
Labels: priority.low, type.accepted, type.bug

#147 Fix minor issues in UG
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: priority.medium, type.documentation

#146 Fix typos in user guide for massblacklist and massdelete
  docs/UserGuide.md
Labels: priority.medium, response.Accepted, type.bug

#152 Fix some UI bugs
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.low, response.Accepted, type.FeatureFlaw

#150 Add test cases for mass blacklist
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/MassBlacklistCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MassBlacklistCommandTest.java
  src/test/java/seedu/address/logic/commands/MassDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MassBlacklistCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, type.codestyle

#151 Improve undo implementation
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/state/AddressBookCommandPair.java
  src/main/java/seedu/address/model/state/State.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/state/StateTest.java
Labels: priority.medium, response.Accepted, type.FeatureFlaw

#153 Fix ability to remove remark.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, response.Accepted, type.FeatureFlaw

#154 Update blacklist
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/BlacklistCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/BlacklistCommandTest.java
Labels: priority.high, type.bug

#148 Fix saving preference for light and dark mode
  src/main/java/seedu/address/commons/core/CssSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: bug, priority.medium, response.Accepted

#157 Update UserGuide for mode of contact
  docs/UserGuide.md
Labels: documentation

#155 Update isSamePerson method
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.low, response.Accepted, type.FeatureFlaw

#158 Reorganise guides and add table of contents
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.high, type.documentation

#160 Update DG for light and dark command
  docs/DeveloperGuide.md
  docs/diagrams/DarkActivityDiagram.puml
  docs/diagrams/DarkSequenceDiagram.puml
  docs/diagrams/LightActivityDiagram.puml
  docs/diagrams/LightSequenceDiagram.puml
  docs/images/DarkActivityDiagram.png
  docs/images/DarkSequenceDiagram.png
  docs/images/LightActivityDiagram.png
  docs/images/LightSequenceDiagram.png
Labels: documentation

#162 Remove other isSamePerson checks
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: priority.high, type.bug

#159 Update dg
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/NavigatingPrevCommandsActivityDiagramDown.puml
  docs/diagrams/NavigatingPrevCommandsActivityDiagramUp.puml
  docs/images/FindActivityDiagram.png
  docs/images/NavigatingPrevCommandsActivityDiagramDown.png
  docs/images/NavigatingPrevCommandsActivityDiagramUp.png
Labels: priority.high, type.documentation

#163 Update guides
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CollectSequenceDiagram.puml
  docs/images/CollectSequenceDiagram.png
  docs/team/ampan98.md
Labels: priority.high, type.documentation

#168 Add project portfolio page
  docs/images/jqchong.png
  docs/team/jqchong.md
Labels: priority.high, type.documentation

#169 Improve code quality
  docs/DeveloperGuide.md
  docs/diagrams/MassBlacklistActivityDiagram.puml
  docs/diagrams/MassBlacklistSequenceDiagram.puml
  docs/images/MassBlacklistSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MassBlacklistCommand.java
  src/main/java/seedu/address/logic/commands/MassDeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MassBlacklistCommandParser.java
  src/main/java/seedu/address/logic/parser/MassDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/comparator/PersonComparator.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/MassBlacklistCommandTest.java
  src/test/java/seedu/address/logic/commands/MassDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/comparator/PersonComparatorTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, type.codestyle

#170 Fix developer guide errors
  docs/DeveloperGuide.md
  docs/diagrams/MassBlacklistActivityDiagram.puml
  docs/images/MassBlacklistActivityDiagram.png
Labels: priority.high, type.documentation

#172 Add project portfolio page
  docs/team/icebear789.md
  docs/team/johndoe.md
Labels: priority.high, type.documentation

#175 Update user guide
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/massBlacklist1.png
  docs/images/massBlacklist2.png
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.high, type.documentation

#176 Update developer guide
  docs/DeveloperGuide.md
Labels: priority.high, type.documentation

#174 Add Project Portfolio
  docs/team/rjeez.md
Labels: type.documentation

#177 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.documentation

#173 Update Userguide
  docs/UserGuide.md
  docs/images/email.png
  docs/images/findAlexDavid.png
  docs/images/house.png
  docs/images/smartphone.png
  docs/team/rjeez.md
Labels: type.documentation

#167 Add test cases for saving data
  docs/DeveloperGuide.md
Labels: priority.high, type.documentation

#178 Improve documentation and fix bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/icebear789.md
  src/main/java/seedu/address/logic/commands/MassBlacklistCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high, type.documentation

#179 Fix consistency issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/BlacklistedContact.png
  docs/images/Ui.png
  docs/team/ampan98.md
  docs/team/icebear789.md
  docs/team/jqchong.md
  docs/team/rjeez.md
Labels: priority.high, type.documentation

#181 Add page breaks
  docs/DeveloperGuide.md
Labels: priority.high, type.documentation

#182 Improve documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MassBlacklistActivityDiagram.puml
  docs/images/BlacklistState2.png
  docs/images/MassBlacklistActivityDiagram.png
  docs/team/icebear789.md
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.high, type.documentation

#183 Fix consistency issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ampan98.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BlacklistCommand.java
  src/main/java/seedu/address/logic/commands/CollectCommand.java
Labels: priority.high, type.documentation

#185 Add examples for blacklist and collect
  docs/UserGuide.md
  docs/team/ampan98.md
  docs/team/icebear789.md
Labels: priority.high, type.documentation

#186 Fix ppp typo
  docs/team/jqchong.md
Labels: type.documentation

#187 Update _base.scss
  docs/_sass/minima/_base.scss
Labels: type.bug, type.documentation

#188 Clarify requirements
  docs/DeveloperGuide.md
Labels: priority.high, type.documentation

#189 Update Project Portfolio
  docs/team/rjeez.md
Labels: documentation

#190 Specify limitations in UG
  docs/UserGuide.md
Labels: priority.high, type.documentation
